
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 114
#define YY_END_OF_BUFFER 115
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[392] =
    {   0,
        0,    0,    0,    0,    0,    0,  115,  113,  112,   92,
      109,    1,   98,   91,  113,   86,   87,   96,   95,   83,
       94,   90,   97,   49,   48,   84,   80,   99,   85,  100,
      103,   46,   46,   88,   89,  101,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   81,  102,   82,   93,  105,  108,  105,  111,  114,
      110,   79,    0,   57,    0,    1,   65,   82,   74,   66,
        0,    0,   63,   71,   61,   72,   62,   73,    0,   52,
      104,  107,   64,   53,   49,    0,    0,   49,   49,    0,
       49,   48,   48,   48,   48,   89,   81,   88,   70,   76,

       78,   77,   69,   46,    0,    0,   67,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,    8,   46,   46,   46,   46,   46,   46,   14,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   68,   75,  106,   57,    0,    0,    0,    0,    0,
       50,    0,    0,    0,   58,    0,   52,    0,   53,    0,
       51,   49,   49,   49,   49,    0,   47,   48,   48,   48,
       48,   60,   59,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   33,   46,   46,   16,   46,   46,   46,

       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,    0,    0,    0,    0,    0,   52,    0,
       53,   51,   49,    0,    0,   47,    0,   47,   47,   48,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
        2,    3,   32,   46,   46,   46,   46,   34,   10,   46,
       46,   13,   46,   17,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   29,   46,   46,    0,
        0,    0,    0,    0,    0,   47,   47,    0,   54,   47,
       47,   46,   46,   38,   46,   46,   46,   46,   46,   46,
       46,    5,   46,   46,   46,   46,   12,   46,   46,   46,

       46,   21,   46,   46,   46,   46,   46,   46,   27,   46,
       46,   31,    0,   55,    0,   56,   54,   47,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,    9,
       11,   15,   46,   46,   20,   22,   23,   24,    4,   25,
       46,   46,   46,   55,   56,   46,   46,   37,   46,   46,
       46,   46,   46,   46,   46,   46,    7,   46,   46,   26,
       46,   46,   35,   36,   39,   40,   46,   46,   46,   46,
       45,    6,   18,   19,   28,   30,   46,   42,   46,   46,
       41,   46,   46,   46,   46,   46,   46,   46,   44,   43,
        0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   20,   19,   19,   19,   21,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   36,   36,   38,   36,   39,   36,   40,
       36,   36,   41,   42,   43,   36,   36,   44,   36,   36,
       45,   46,   47,   48,   49,    1,   50,   51,   52,   53,

       54,   55,   56,   57,   58,   36,   36,   59,   60,   61,
       62,   63,   36,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[77] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    6,    6,
        7,    7,    1,    1,    1,    1,    1,    3,    7,    7,
        7,    7,    7,    7,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    1,    3,    1,    1,    8,    6,
        6,    7,    7,    7,    6,    8,    8,    8,    8,    8,
        9,    8,    8,    9,    8,    9,    8,    9,    8,    9,
        8,    8,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[404] =
    {   0,
        0,    0,   74,   75,   76,   77,  738,  739,  739,  711,
       78,    0,   58,   80,  690,  739,  739,  709,   76,  739,
       77,   75,   88,  109,  164,  707,  739,   92,  707,   81,
      739,    0,  104,  739,  739,  706,  109,  664,   99,   36,
       51,   57,  668,   65,  667,  674,  108,  656,  150,  664,
      668,  739,   96,  739,  739,  739,  739,  707,  739,  739,
      739,  739,  118,  170,  117,    0,  739,  739,  739,  739,
      123,  170,  739,  739,  739,  739,  739,  739,  707,  208,
      739,  739,  739,  214,   90,  237,  259,  124,   95,  706,
      150,    0,  157,  119,  153,  739,  739,  739,  695,  739,

      739,  739,  694,    0,  176,  673,  739,  133,  656,  655,
      662,  655,  652,  647,  655,  656,  644,  644,  658,  646,
      651,  638,  639,  636,  636,  639,  636,  633,    0,  135,
      637,  149,  635,  147,  175,  638,  632,  689,  180,  185,
      635,  739,  739,  739,  280,  687,  244,  270,  279,    0,
      739,  283,  286,    0,  739,  315,  739,  330,  739,  289,
      320,  233,  739,  653,  631,    0,  328,  250,  739,  651,
      629,  739,  739,  629,  624,  623,  624,  622,  632,  617,
      630,  615,  611,  615,  622,  611,  185,  614,  612,  607,
      597,  602,  604,    0,  580,  582,    0,  575,  564,  535,

      533,  535,  536,  542,  529,  527,  527,  538,  529,  532,
      536,  538,  528,  354,  396,  337,  443,  342,  385,  390,
      448,  739,  739,  158,  224,  327,  491,  256,  253,  739,
      530,  525,  525,  520,  528,  523,  524,  508,  519,  511,
        0,    0,    0,  504,  511,  501,  508,    0,    0,  502,
      494,    0,  497,    0,  492,  492,  489,  486,  497,  487,
      470,  475,  473,  465,  456,  459,    0,  442,  451,  281,
        0,  344,    0,  501,  511,  326,  739,  413,  516,  464,
      442,  439,  441,    0,  433,  427,  432,  422,  429,  435,
      432,    0,  422,  422,  426,  418,    0,  424,  405,  402,

      398,    0,  405,  390,  391,  375,  382,  384,    0,  376,
      378,    0,  435,  521,  526,  543,  739,  739,  154,  372,
      368,  363,  359,  346,  350,  346,  349,  330,  330,    0,
        0,    0,  338,  337,    0,    0,    0,    0,    0,    0,
      333,  332,  326,  739,  739,  319,  327,    0,  311,  328,
      328,  313,  327,  318,  282,  272,    0,  260,  256,    0,
      268,  265,    0,    0,    0,    0,  250,  252,  221,  207,
        0,    0,    0,    0,    0,    0,  190,    0,  195,  192,
        0,  145,  154,   91,   93,   77,   52,   35,    0,    0,
      739,  602,  611,  620,  629,  638,  642,  649,  656,  661,

      663,  665,  667
    } ;

static yyconst flex_int16_t yy_def[404] =
    {   0,
      391,    1,  392,  392,  393,  393,  391,  391,  391,  391,
      394,  395,  391,  391,  396,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  397,  397,  391,  391,  391,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  394,  391,  398,  395,  391,  391,  391,  391,
      396,  399,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,   24,  391,  391,  391,  391,  400,
      391,   25,  391,  391,  391,  391,  391,  391,  391,  391,

      391,  391,  391,  397,  394,  396,  391,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  391,  391,  391,  391,  391,  391,  394,  394,  401,
      391,  396,  396,  402,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  403,  400,  391,  391,  391,
      391,  391,  391,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,

      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  394,  394,  396,  396,  391,  391,  391,
      391,  391,  391,  403,  403,  391,  391,  391,  391,  391,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  394,
      215,  396,  217,  391,  391,  391,  391,  391,  391,  391,
      391,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,

      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  391,  391,  391,  391,  391,  391,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  391,  391,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
        0,  391,  391,  391,  391,  391,  391,  391,  391,  391,

      391,  391,  391
    } ;

static yyconst flex_int16_t yy_nxt[816] =
    {   0,
        8,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   25,
       25,   25,   26,   27,   28,   29,   30,   31,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   33,   32,   32,
       32,   32,   33,   32,   34,    8,   35,   36,   37,   38,
       32,   39,   40,   41,   42,   43,   32,   44,   45,   32,
       32,   32,   32,   46,   47,   48,   49,   50,   51,   32,
       32,   32,   52,   53,   54,   55,   57,   57,   60,   60,
       61,   61,   64,   67,   68,   58,   58,   69,   74,  121,
       79,   76,   80,   80,   80,   80,   80,  122,   97,   81,

      390,   75,   77,   78,   82,   70,  102,  103,  105,  123,
      389,  124,  106,   83,   98,  126,   99,  100,  127,  129,
      125,  142,   64,   65,   84,  130,   85,   85,   85,   86,
       86,  151,  164,  391,  148,  148,  149,  108,  109,  110,
      388,   87,  387,  111,  386,  112,   88,  113,  118,  114,
      115,   89,   90,  165,  105,  119,  170,  116,  106,  391,
      120,  162,   87,   65,  133,  134,  163,   91,   72,  143,
      138,  145,  145,  135,  105,   89,  136,  171,   90,   84,
       64,   92,   92,   92,   92,   92,  150,  152,  152,  153,
      163,  174,  163,  196,  168,  169,   87,  274,  175,  169,

      197,   93,  203,  346,  199,  385,   94,  146,  162,  384,
      139,  168,  146,  200,  201,  347,  163,   87,  204,  169,
      274,   65,   95,  169,  205,   80,   80,   80,   80,   80,
       94,   80,   80,   80,   80,   80,  147,  209,  206,  154,
      156,  157,  211,  212,  210,  157,  158,  159,  105,  244,
      245,  159,   84,  383,   86,   86,   86,   86,   86,  382,
      381,  156,  157,  275,  146,  380,  157,  158,  159,   87,
      379,  160,  159,  160,   64,  163,  161,  161,  161,  161,
      161,  145,  145,   64,  105,   64,  275,  214,  214,  214,
       87,  151,  169,  280,  151,  277,  214,  214,  214,  163,

      216,  216,  216,  216,  216,  216,  161,  161,  161,  161,
      161,  276,  378,  377,  281,   65,  169,  146,  376,  277,
      375,  374,  146,  373,   65,  372,   65,  218,   72,  218,
      371,   72,  219,  219,  219,  219,  219,  161,  161,  161,
      161,  161,  220,  225,  220,  151,  147,  221,  221,  221,
      221,  221,  151,  222,  272,  272,  272,  222,   64,  219,
      219,  219,  219,  219,  276,  226,  370,  227,  277,  277,
      228,  270,  270,  270,  222,  369,  368,  367,  222,  366,
      365,  364,   72,  363,  362,  361,  229,  360,  359,   72,
      227,  358,  277,  277,  228,  357,  356,  355,  354,   65,

       64,  353,  219,  219,  219,  219,  219,  221,  221,  221,
      221,  221,  352,  271,  271,  271,  271,  271,  157,  351,
      350,  349,  157,  348,  271,  271,  271,  271,  271,  271,
      279,  279,  279,  279,  279,  343,  342,  341,  340,  157,
      339,   65,  338,  157,  337,  271,  271,  271,  271,  271,
      271,  151,  314,  314,  314,  314,  314,  336,  335,  334,
      273,  273,  273,  273,  273,  221,  221,  221,  221,  221,
      333,  273,  273,  273,  273,  273,  273,  332,  331,  330,
      329,  159,  328,  327,  326,  159,  325,  324,   72,  323,
      322,  321,  273,  273,  273,  273,  273,  273,  320,  319,

      318,  318,  159,  278,  312,  278,  159,  311,  279,  279,
      279,  279,  279,  313,  310,  313,  309,  308,  314,  314,
      314,  314,  314,  315,  307,  315,  306,  305,  316,  316,
      316,  316,  316,  279,  279,  279,  279,  279,  314,  314,
      314,  314,  314,  316,  316,  316,  316,  316,  304,  317,
      303,  302,  301,  317,  344,  300,  299,  298,  344,  297,
      316,  316,  316,  316,  316,  296,  295,  294,  293,  292,
      317,  291,  290,  289,  317,  344,  345,  288,  287,  344,
      345,  286,  285,  284,  283,  282,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  345,  258,  257,

      256,  345,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       63,  255,   63,   63,   63,   63,   63,   63,   63,   66,
      254,   66,   66,   66,   66,   66,   66,   66,   71,  253,
       71,  252,   71,   71,   71,   71,   71,  104,  104,  104,
      104,   63,   63,  251,   63,  250,  249,   63,   71,   71,
      248,   71,  247,  246,   71,  167,  167,  167,  215,  215,
      217,  217,  224,  224,  243,  242,  241,  240,  239,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  230,  223,
      223,  105,  213,  105,  208,  207,  202,  198,  195,  194,

      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  176,   72,  173,
      172,  166,  155,  144,  141,  140,  137,  132,  131,  128,
      117,  107,  101,   96,   73,   72,   62,  391,    7,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,

      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391
    } ;

static yyconst flex_int16_t yy_chk[816] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,    5,    6,
        5,    6,   11,   13,   13,    3,    4,   14,   19,   40,
       22,   21,   22,   22,   22,   22,   22,   40,   28,   23,

      388,   19,   21,   21,   23,   14,   30,   30,   33,   41,
      387,   41,   33,   23,   28,   42,   28,   28,   42,   44,
       41,   53,   63,   11,   24,   44,   24,   24,   24,   24,
       24,   71,   89,   85,   65,   65,   65,   37,   37,   37,
      386,   24,  385,   37,  384,   37,   24,   37,   39,   37,
       37,   24,   24,   89,   49,   39,   94,   37,   49,   85,
       39,   88,   24,   63,   47,   47,   88,   24,   71,   53,
       49,   64,   64,   47,   64,   24,   47,   94,   24,   25,
      105,   25,   25,   25,   25,   25,   65,   72,   72,   72,
       88,  108,   91,  130,   93,   95,   25,  224,  108,   93,

      130,   25,  134,  319,  132,  383,   25,   64,   91,  382,
       49,   95,   64,  132,  132,  319,   91,   25,  134,   95,
      224,  105,   25,   93,  135,   80,   80,   80,   80,   80,
       25,   84,   84,   84,   84,   84,   64,  139,  135,   72,
       80,   80,  140,  140,  139,   80,   84,   84,  147,  187,
      187,   84,   86,  380,   86,   86,   86,   86,   86,  379,
      377,   80,   80,  225,  147,  370,   80,   84,   84,   86,
      369,   87,   84,   87,  148,  162,   87,   87,   87,   87,
       87,  145,  145,  149,  145,  270,  225,  148,  148,  148,
       86,  152,  168,  228,  153,  229,  149,  149,  149,  162,

      152,  152,  152,  153,  153,  153,  160,  160,  160,  160,
      160,  229,  368,  367,  228,  148,  168,  145,  362,  229,
      361,  359,  145,  358,  149,  356,  270,  156,  152,  156,
      355,  153,  156,  156,  156,  156,  156,  161,  161,  161,
      161,  161,  158,  167,  158,  216,  145,  158,  158,  158,
      158,  158,  272,  161,  216,  216,  216,  161,  214,  218,
      218,  218,  218,  218,  226,  167,  354,  167,  276,  226,
      167,  214,  214,  214,  161,  353,  352,  351,  161,  350,
      349,  347,  216,  346,  343,  342,  167,  341,  334,  272,
      167,  333,  276,  226,  167,  329,  328,  327,  326,  214,

      215,  325,  219,  219,  219,  219,  219,  220,  220,  220,
      220,  220,  324,  215,  215,  215,  215,  215,  219,  323,
      322,  321,  219,  320,  215,  215,  215,  215,  215,  215,
      278,  278,  278,  278,  278,  311,  310,  308,  307,  219,
      306,  215,  305,  219,  304,  215,  215,  215,  215,  215,
      215,  217,  313,  313,  313,  313,  313,  303,  301,  300,
      217,  217,  217,  217,  217,  221,  221,  221,  221,  221,
      299,  217,  217,  217,  217,  217,  217,  298,  296,  295,
      294,  221,  293,  291,  290,  221,  289,  288,  217,  287,
      286,  285,  217,  217,  217,  217,  217,  217,  283,  282,

      281,  280,  221,  227,  269,  227,  221,  268,  227,  227,
      227,  227,  227,  274,  266,  274,  265,  264,  274,  274,
      274,  274,  274,  275,  263,  275,  262,  261,  275,  275,
      275,  275,  275,  279,  279,  279,  279,  279,  314,  314,
      314,  314,  314,  315,  315,  315,  315,  315,  260,  279,
      259,  258,  257,  279,  314,  256,  255,  253,  314,  251,
      316,  316,  316,  316,  316,  250,  247,  246,  245,  244,
      279,  240,  239,  238,  279,  314,  316,  237,  236,  314,
      316,  235,  234,  233,  232,  231,  213,  212,  211,  210,
      209,  208,  207,  206,  205,  204,  203,  316,  202,  201,

      200,  316,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      394,  199,  394,  394,  394,  394,  394,  394,  394,  395,
      198,  395,  395,  395,  395,  395,  395,  395,  396,  196,
      396,  195,  396,  396,  396,  396,  396,  397,  397,  397,
      397,  398,  398,  193,  398,  192,  191,  398,  399,  399,
      190,  399,  189,  188,  399,  400,  400,  400,  401,  401,
      402,  402,  403,  403,  186,  185,  184,  183,  182,  181,
      180,  179,  178,  177,  176,  175,  174,  171,  170,  165,
      164,  146,  141,  138,  137,  136,  133,  131,  128,  127,

      126,  125,  124,  123,  122,  121,  120,  119,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  106,  103,
       99,   90,   79,   58,   51,   50,   48,   46,   45,   43,
       38,   36,   29,   26,   18,   15,   10,    7,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,

      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "parse.l"
#line 25 "parse.l"
#include "parse.tab.h"
#include "libs/html.h"
#include <stdio.h>
   

extern int sym_type(const char *);  /* returns type from symbol table */

#define sym_type(identifier) IDENTIFIER /* with no symbol table, fake it */

static int check_type(void);

    //"return"				{yylval.nom=strdup(yytext); return(RETURN); }
//";"					{yylval.nom=strdup(yytext); return ';'; }

/*
  "continue"              {fprintf(f_output,yylval.nom=strdup(yytext); return(CONTINUE);}
"break"                 {fprintf(f_output,yylval.nom=strdup(yytext); return(BREAK);}
"return"                {fprintf(f_output,yylval.nom=strdup(yytext); return(RETURN);}
("{"|"<%")				{ fprintf(f_output,"%s",yytext); return '{'; }
("}"|"%>")				{ fprintf(f_output,"%s",yytext); return '}'; }

*/

/*
 Avec ';' , Ca fonctionne lorsque l'on fait une declaration de variable ( etc int x=3;) ou que l'on fait une declaration de fonction ( ex : int coucou();) mais pas quand on écrit un ';' après une expression.
 Lorsque l'on veut implementer return, il faut aussi implementer ';' et le '}' mais il faut aussi implémenter ceux qui dependent de '}' ... <<<< Je comprends rien
*/    


#line 807 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define STRING 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 57 "parse.l"




#line 1001 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 392 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 739 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 61 "parse.l"
{/*On efface les include et tous ce qui est apres*/}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 62 "parse.l"
{print_balise_span("type_specifier","auto"); return AUTO; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 63 "parse.l"
{print_balise_span("jaune","case"); return  CASE;} 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 64 "parse.l"
{print_balise_span("type_specifier","struct"); return  STRUCT;} 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 65 "parse.l"
{print_balise_span("type_specifier","const");  return  CONST;} 
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 66 "parse.l"
{print_balise_span("type_specifier","continue"); return  CONTINUE;} 
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "parse.l"
{print_balise_span("type_specifier","default"); return  DEFAULT;} 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 68 "parse.l"
{print_balise_span("jump_statement","do"); return  DO;} 
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 69 "parse.l"
{print_balise_span("type_specifier","double");yylval.val="double";return  DOUBLE;} 
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 70 "parse.l"
{print_balise_span("type_specifier","enum"); return  ENUM;} 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 71 "parse.l"
{print_balise_span("type_specifier","extern"); return  EXTERN;} 
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 72 "parse.l"
{print_balise_span("type_specifier","float"); yylval.val="float";return  FLOAT;} 
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 74 "parse.l"
{print_balise_span("type_specifier","goto"); return  GOTO;} 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 75 "parse.l"
{print_balise_span("jaune","if"); return  IF;} 
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 76 "parse.l"
{print_balise_span("type_specifier","inline"); return  INLINE;} 
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 77 "parse.l"
{print_balise_span("type_specifier","int"); yylval.val="int";return  INT;} 
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 78 "parse.l"
{print_balise_span("type_specifier","long"); return  LONG;} 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 79 "parse.l"
{print_balise_span("type_specifier","register");yylval.val="long"; return  REGISTER;} 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 80 "parse.l"
{print_balise_span("type_specifier","restrict"); return  RESTRICT;} 
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 81 "parse.l"
{print_balise_span("jaune","return"); return  RETURN;} 
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 82 "parse.l"
{print_balise_span("type_specifier","short"); yylval.val="short";return  SHORT;} 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 83 "parse.l"
{print_balise_span("type_specifier","signed"); yylval.val="signed";return  SIGNED;} 
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 84 "parse.l"
{print_balise_span("jump_statement","sizeof"); return  SIZEOF;} 
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 85 "parse.l"
{print_balise_span("type_specifier","static"); return  STATIC;} 
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 86 "parse.l"
{print_balise_span("jaune","switch"); return  SWITCH;} 
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 87 "parse.l"
{print_balise_span("type_specifier","typedef");  return  TYPEDEF;} 
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 88 "parse.l"
{print_balise_span("type_specifier","union"); return  UNION;} 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 89 "parse.l"
{print_balise_span("type_specifier","unsigned"); return  UNSIGNED;} 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 90 "parse.l"
{print_balise_span("type_specifier","void"); yylval.val="void";return  VOID;} 
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 91 "parse.l"
{print_balise_span("type_specifier","volatile");return  VOLATILE;} 
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 92 "parse.l"
{print_balise_span("type_specifier","while");return  WHILE;} 
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 95 "parse.l"
{print_balise_span("type_specifier","char");yylval.val="char";return  CHAR;} 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 96 "parse.l"
{print_balise_span("jaune","for");return  FOR;} 
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 97 "parse.l"
{print_balise_span("jaune","else");return  ELSE;} 
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 100 "parse.l"
{ fprintf(f_output,"%s",yytext); return ALIGNAS; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 101 "parse.l"
{ fprintf(f_output,"%s",yytext); return ALIGNOF; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 102 "parse.l"
{ fprintf(f_output,"%s",yytext); return ATOMIC; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 103 "parse.l"
{ fprintf(f_output,"%s",yytext); return BOOL; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 104 "parse.l"
{ fprintf(f_output,"%s",yytext); return COMPLEX; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 105 "parse.l"
{ fprintf(f_output,"%s",yytext); return GENERIC; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 106 "parse.l"
{ fprintf(f_output,"%s",yytext); return IMAGINARY; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 107 "parse.l"
{ fprintf(f_output,"%s",yytext); return NORETURN; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 108 "parse.l"
{ fprintf(f_output,"%s",yytext); return STATIC_ASSERT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 109 "parse.l"
{ fprintf(f_output,"%s",yytext); return THREAD_LOCAL; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 110 "parse.l"
{ fprintf(f_output,"%s",yytext); return FUNC_NAME; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 115 "parse.l"
{yylval.val=strdup(yytext); return check_type(); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 117 "parse.l"
{ fprintf(f_output,"%s",yytext); return I_CONSTANT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 118 "parse.l"
{ fprintf(f_output,"%s",yytext); return I_CONSTANT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 119 "parse.l"
{ fprintf(f_output,"%s",yytext); return I_CONSTANT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 120 "parse.l"
{ fprintf(f_output,"%s",yytext); return I_CONSTANT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 123 "parse.l"
{ fprintf(f_output,"%s",yytext); return F_CONSTANT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 124 "parse.l"
{ print_balise_span("nombre",yytext); return F_CONSTANT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 125 "parse.l"
{ fprintf(f_output,"%s",yytext); return F_CONSTANT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 126 "parse.l"
{ fprintf(f_output,"%s",yytext); return F_CONSTANT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 127 "parse.l"
{ fprintf(f_output,"%s",yytext); return F_CONSTANT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 128 "parse.l"
{ fprintf(f_output,"%s",yytext); return F_CONSTANT; }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 130 "parse.l"
{ fprintf(f_output,"%s",yytext); return STRING_LITERAL; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 132 "parse.l"
{ fprintf(f_output,"%s",yytext); return ELLIPSIS; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 133 "parse.l"
{ fprintf(f_output,"%s",yytext); return RIGHT_ASSIGN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 134 "parse.l"
{ fprintf(f_output,"%s",yytext); return LEFT_ASSIGN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 135 "parse.l"
{ fprintf(f_output,"%s",yytext); return ADD_ASSIGN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 136 "parse.l"
{ fprintf(f_output,"%s",yytext); return SUB_ASSIGN; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 137 "parse.l"
{ fprintf(f_output,"%s",yytext); return MUL_ASSIGN; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 138 "parse.l"
{ fprintf(f_output,"%s",yytext); return DIV_ASSIGN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 139 "parse.l"
{ fprintf(f_output,"%s",yytext); return MOD_ASSIGN; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 140 "parse.l"
{ fprintf(f_output,"%s",yytext); return AND_ASSIGN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 141 "parse.l"
{ fprintf(f_output,"%s",yytext); return XOR_ASSIGN; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 142 "parse.l"
{ fprintf(f_output,"%s",yytext); return OR_ASSIGN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 143 "parse.l"
{ fprintf(f_output,"%s",yytext); return RIGHT_OP; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 144 "parse.l"
{ fprintf(f_output,"%s",yytext); return LEFT_OP; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 145 "parse.l"
{ fprintf(f_output,"%s",yytext); return INC_OP; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 146 "parse.l"
{ fprintf(f_output,"%s",yytext); return DEC_OP; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 147 "parse.l"
{ fprintf(f_output,"%s",yytext); return PTR_OP; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 148 "parse.l"
{ fprintf(f_output,"%s",yytext); return AND_OP; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 149 "parse.l"
{ fprintf(f_output,"%s",yytext); return OR_OP; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 150 "parse.l"
{ fprintf(f_output,"%s",yytext); return LE_OP; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 151 "parse.l"
{ fprintf(f_output,"%s",yytext); return GE_OP; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 152 "parse.l"
{ fprintf(f_output,"%s",yytext); return EQ_OP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 153 "parse.l"
{ fprintf(f_output,"%s",yytext); return NE_OP; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 154 "parse.l"
{print_balise_span("vert",";"); return ';'; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 155 "parse.l"
{indent=indent+2;print_balise_span("vert","{"); new_block(NULL);  return '{'; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 156 "parse.l"
{indent=indent-2;print_balise_span("vert","}"); fin_block("block0"); return '}'; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 157 "parse.l"
{ fprintf(f_output,"%s",yytext); return ','; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 158 "parse.l"
{ fprintf(f_output,"%s",yytext); return ':'; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 159 "parse.l"
{ fprintf(f_output,"%s",yytext); return '='; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 160 "parse.l"
{print_balise_span("vert","("); return '('; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 161 "parse.l"
{print_balise_span("vert",")"); return ')'; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 162 "parse.l"
{ fprintf(f_output,"%s",yytext); return '['; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 163 "parse.l"
{ fprintf(f_output,"%s",yytext); return ']'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 164 "parse.l"
{ fprintf(f_output,"%s",yytext); return '.'; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 165 "parse.l"
{ fprintf(f_output,"%s",yytext); return '&'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 166 "parse.l"
{print_balise_span("vert","!"); return '!'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 167 "parse.l"
{ fprintf(f_output,"%s",yytext); return '~'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 168 "parse.l"
{print_balise_span("vert","-"); return '-'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 169 "parse.l"
{print_balise_span("vert","+"); return '+'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 170 "parse.l"
{print_balise_span("vert","*"); return '*'; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 171 "parse.l"
{ fprintf(f_output,"%s",yytext); return '/'; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 172 "parse.l"
{ fprintf(f_output,"%s",yytext); return '%'; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 173 "parse.l"
{ fprintf(f_output,"%s",yytext); return '<'; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 174 "parse.l"
{ fprintf(f_output,"%s",yytext); return '>'; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 175 "parse.l"
{ fprintf(f_output,"%s",yytext); return '^'; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 176 "parse.l"
{ fprintf(f_output,"%s",yytext); return '|'; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 177 "parse.l"
{print_balise_span("vert","?"); return '?'; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 182 "parse.l"
{fprintf(f_output,"<span class=\"comment\">/*");BEGIN(COMMENT);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 183 "parse.l"
{fprintf(f_output,"%c",yytext[0]);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 184 "parse.l"
{fprintf(f_output, "*/</span>");BEGIN(INITIAL);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 186 "parse.l"
{fprintf(f_output,"<span class=\"comment\">//");BEGIN(COMMENT);}
	YY_BREAK
case 108:
/* rule 108 can match eol */
YY_RULE_SETUP
#line 187 "parse.l"
{fprintf(f_output,"</span><br \\>");int i=0;while(i<indent){fprintf(f_output,"&nbsp;");i++;};BEGIN(INITIAL);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 190 "parse.l"
{fprintf(f_output,"<span class=\"string\">\"");BEGIN(STRING);}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 191 "parse.l"
{fprintf(f_output,"\"</span>");BEGIN(INITIAL);}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 192 "parse.l"
{fprintf(f_output,"%c",yytext[0]);}
	YY_BREAK
case 112:
/* rule 112 can match eol */
YY_RULE_SETUP
#line 194 "parse.l"
{fprintf(f_output,"<br \\>\n");nb_ligne++;fprintf(f_output,"<span class=\"numerotation\">%d.  </span>",nb_ligne);int i=0;while(i<indent){fprintf(f_output,"&nbsp;");i++;}}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 195 "parse.l"
{fprintf(f_output,"%c",yytext[0]);}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 198 "parse.l"
ECHO;
	YY_BREAK
#line 1657 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 392 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 392 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 391);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 198 "parse.l"


  /*
    Si un mot n'est ni un typedef ou enum
    alors c'est un identifier */
static int check_type(void)
{
	fprintf(f_output,"%s",yytext);  
  switch (sym_type(yytext))
    {
    case TYPEDEF_NAME:                /* previously defined */
        return TYPEDEF_NAME;
    case ENUMERATION_CONSTANT:        /* previously defined */
        return ENUMERATION_CONSTANT;
    default:                          /* includes undefined */
        return IDENTIFIER;
    }
}

