
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 108
#define YY_END_OF_BUFFER 109
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[386] =
    {   0,
        0,    0,  109,  107,  106,  106,   94,  107,  100,   93,
      107,   88,   89,   98,   97,   85,   96,   92,   99,   51,
       50,   86,   82,  101,   87,  102,  105,   48,   48,   90,
       91,  103,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   83,  104,
       84,   95,   81,    0,   59,    0,   67,   84,   76,   68,
        0,    0,   65,   73,   63,   74,   64,   75,    0,   54,
        1,    2,   66,   55,   51,    0,    0,   51,   51,    0,
       51,   50,   50,   50,   50,   91,   83,   90,   72,   78,
       80,   79,   71,   48,    0,    0,   69,   48,   48,   48,

       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   10,   48,   48,   48,   48,   48,   48,   18,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   70,   77,   59,    0,    0,    0,    0,    0,
       52,    0,    0,    0,   60,    0,   54,    2,    0,   55,
        0,   53,   51,   51,   51,   51,    0,   49,   50,   50,
       50,   50,   62,   61,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   16,   48,   48,   20,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,

       48,   48,   48,   48,   48,    0,    0,    0,    0,    0,
       54,    0,   55,   53,   51,    0,    0,   49,    0,   49,
       49,   50,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,    3,   48,    5,    6,   48,   48,   48,   48,
       12,   13,   48,   48,   17,   48,   21,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   34,
       48,   48,    0,    0,    0,    0,    0,    0,   49,   49,
        0,   56,   49,   49,   48,   48,   40,   48,   48,   48,
       48,   48,   48,   48,    4,    7,   48,   48,   48,   48,
       15,   48,   48,   48,   48,   25,   48,   48,   48,   48,

       48,   48,   32,   48,   48,   36,    0,   57,    0,   58,
       56,   49,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   11,   14,   19,   48,   48,   24,   26,
       27,   28,   29,   30,   48,   48,   48,   57,   58,   48,
       48,   39,   48,   48,   48,   48,   48,   48,   48,   48,
        9,   48,   48,   31,   48,   48,   37,   38,   41,   42,
       48,   48,   48,   48,   47,    8,   22,   23,   33,   35,
       48,   44,   48,   48,   43,   48,   48,   48,   48,   48,
       48,   48,   46,   45,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   19,   18,   18,   18,   20,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   35,   35,   37,   35,   38,   35,   39,
       35,   35,   40,   41,   42,   35,   35,   43,   35,   35,
       44,   45,   46,   47,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   35,   58,   59,   60,   61,
       62,   63,   35,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[77] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    5,    1,    6,    6,    6,    7,
        7,    1,    1,    1,    1,    1,    3,    7,    7,    7,
        7,    7,    7,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    1,    3,    1,    1,    8,    6,    6,
        7,    7,    7,    6,    8,    8,    8,    8,    8,    8,
        9,    8,    8,    9,    8,    9,    8,    9,    8,    9,
        8,    8,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[396] =
    {   0,
        0,    0,  715,  716,  716,  716,  689,   72,   53,   73,
      668,  716,  716,  687,   69,  716,   70,   68,   81,  103,
      159,  685,  716,   85,  685,   74,  716,    0,   85,  716,
      716,  684,  103,  641,  643,   52,   49,   66,   53,  644,
       65,  643,  651,   47,  632,  144,  640,  645,  716,   80,
      716,  716,  716,  123,  155,  164,  716,  716,  716,  716,
      121,  167,  716,  716,  716,  716,  716,  716,  685,  196,
      716,    0,  716,  221,   91,  244,  190,  105,  116,  684,
       96,    0,  152,  128,  164,  716,  716,  716,  673,  716,
      716,  716,  672,    0,  143,  651,  716,  134,  633,  632,

      640,  632,  629,  624,  633,  634,  621,  633,  620,  635,
      622,  628,  614,  615,  612,  612,  615,  612,  609,    0,
      161,  613,  170,  611,   95,  181,  615,  608,  665,  133,
      112,  612,  716,  716,  241,  663,  227,  251,  267,    0,
      716,  271,  274,    0,  716,  286,  716,    0,  303,  716,
      308,  313,  157,  716,  630,  607,    0,  298,  206,  716,
      628,  605,  716,  716,  606,  600,  599,  600,  598,  609,
      593,  607,  591,  587,  591,  603,  598,  586,  186,  600,
      598,  594,  586,  592,  595,    0,  581,  585,    0,  586,
      583,  573,  571,  557,  557,  564,  549,  544,  544,  555,

      534,  537,  533,  533,  522,  334,  375,  330,  422,  324,
      364,  369,  427,  716,  716,  218,  232,  331,  470,  240,
      332,  716,  525,  519,  518,  513,  522,  519,  520,  506,
      518,  509,    0,  511,    0,    0,  502,  510,  499,  506,
        0,    0,  500,  497,    0,  501,    0,  494,  494,  492,
      487,  499,  489,  493,  497,  496,  494,  479,  484,    0,
      471,  483,  309,    0,  310,    0,  480,  490,  269,  716,
      392,  495,  498,  474,  470,  473,    0,  470,  453,  449,
      439,  446,  447,  444,    0,    0,  432,  426,  430,  419,
        0,  426,  412,  420,  409,    0,  417,  414,  415,  399,

      407,  409,    0,  400,  402,    0,  414,  501,  506,  524,
      716,  716,  307,  407,  404,  399,  388,  371,  386,  384,
      374,  354,  353,    0,    0,    0,  364,  365,    0,    0,
        0,    0,    0,    0,  361,  361,  343,  716,  716,  335,
      324,    0,  307,  325,  322,  306,  318,  316,  315,  309,
        0,  296,  293,    0,  306,  257,    0,    0,    0,    0,
      245,  241,  252,  235,    0,    0,    0,    0,    0,    0,
      216,    0,  202,  204,    0,  195,  170,  150,  146,   95,
       71,   16,    0,    0,  716,  583,  592,  596,  603,  610,
      619,  624,  626,  628,  630

    } ;

static yyconst flex_int16_t yy_def[396] =
    {   0,
      385,    1,  385,  385,  385,  385,  385,  386,  385,  385,
      387,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  388,  388,  385,
      385,  385,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  385,  385,
      385,  385,  385,  386,  385,  389,  385,  385,  385,  385,
      387,  390,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  391,  385,  385,   20,  385,  385,  385,  385,  392,
      385,   21,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  388,  386,  387,  385,  388,  388,  388,

      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  385,  385,  385,  385,  385,  386,  386,  393,
      385,  387,  387,  394,  385,  385,  385,  391,  385,  385,
      385,  385,  385,  385,  385,  385,  395,  392,  385,  385,
      385,  385,  385,  385,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,

      388,  388,  388,  388,  388,  386,  386,  387,  387,  385,
      385,  385,  385,  385,  385,  395,  395,  385,  385,  385,
      385,  385,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  386,  207,  387,  209,  385,  385,  385,  385,
      385,  385,  385,  385,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,

      388,  388,  388,  388,  388,  388,  385,  385,  385,  385,
      385,  385,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  385,  385,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,    0,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385

    } ;

static yyconst flex_int16_t yy_nxt[793] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       21,   22,   23,   24,   25,   26,   27,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   29,   28,   28,   28,
       28,   29,   28,   30,    4,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   28,   41,   28,   42,   28,
       28,   28,   28,   43,   44,   45,   46,   47,   48,   28,
       28,   28,   49,   50,   51,   52,   55,   57,   58,   59,
       64,  384,   69,   66,   70,   70,   70,   70,   70,   95,
       87,   71,   96,   65,   67,   68,   72,   60,   92,   93,

      109,  112,  124,  125,  133,   73,   88,  110,   89,   90,
      113,  117,  126,  111,  118,  127,   56,   74,  120,   75,
       75,   75,   76,   76,  114,  121,  115,   55,  141,  383,
       98,   99,  100,  385,   77,  116,  101,  154,  102,   78,
      103,  153,  104,  105,   79,   80,  154,   55,   95,  195,
      106,   96,  155,  134,  153,   77,  135,  135,  382,   95,
      385,   81,  154,  129,  161,   62,  196,   56,  203,   79,
      204,  154,   80,   74,  156,   82,   82,   82,   82,   82,
      138,  138,  139,  142,  142,  143,  162,   56,  159,  201,
       77,  136,  165,  160,  381,   83,  136,  202,  154,  166,

       84,  151,  380,  151,  130,  160,  152,  152,  152,  152,
      152,   77,   70,   70,   70,   70,   70,   85,  160,  188,
      379,  137,  159,  154,  191,   84,  189,  146,  147,  197,
      160,   95,  147,  140,  192,  193,  144,   70,   70,   70,
       70,   70,  135,  135,  198,   95,  136,  160,  146,  147,
      237,  238,  149,  150,  147,   55,  267,  150,   74,  378,
       76,   76,   76,   76,   76,  377,  376,  206,  206,  206,
      268,   55,  160,  149,  150,   77,  273,  136,  141,  150,
      267,  141,  136,  206,  206,  206,  375,  208,  208,  208,
      208,  208,  208,  374,  268,   56,   77,  210,  274,  210,

      373,  372,  211,  211,  211,  211,  211,  137,  371,  370,
      270,   56,  217,   55,  212,   62,  212,  141,   62,  213,
      213,  213,  213,  213,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  218,  270,  219,  141,   55,  220,
      211,  211,  211,  211,  211,  214,  265,  265,  265,  214,
      263,  263,  263,   56,   62,  340,  221,  369,  368,  367,
      219,  366,  365,  364,  220,  363,  214,  269,  341,  362,
      361,  214,  270,  270,   62,  360,  359,  358,   56,   55,
      211,  211,  211,  211,  211,  213,  213,  213,  213,  213,
      269,  264,  264,  264,  264,  264,  147,  270,  270,  357,

      147,  356,  264,  264,  264,  264,  264,  264,  272,  272,
      272,  272,  272,  355,  354,  353,  352,  147,  351,   56,
      350,  349,  147,  264,  264,  264,  264,  264,  264,  141,
      308,  308,  308,  308,  308,  348,  347,  346,  266,  266,
      266,  266,  266,  213,  213,  213,  213,  213,  345,  266,
      266,  266,  266,  266,  266,  344,  343,  342,  337,  150,
      336,  335,  334,  150,  333,  332,   62,  331,  330,  329,
      266,  266,  266,  266,  266,  266,  328,  327,  326,  325,
      150,  271,  324,  271,  323,  150,  272,  272,  272,  272,
      272,  307,  322,  307,  321,  320,  308,  308,  308,  308,

      308,  309,  319,  309,  318,  317,  310,  310,  310,  310,
      310,  272,  272,  272,  272,  272,  316,  308,  308,  308,
      308,  308,  310,  310,  310,  310,  310,  311,  315,  314,
      313,  311,  312,  338,  312,  306,  305,  338,  304,  303,
      310,  310,  310,  310,  310,  302,  301,  300,  311,  299,
      298,  297,  296,  311,  338,  295,  339,  294,  293,  338,
      339,  292,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  281,  280,  279,  278,  277,  339,  276,  275,
      262,  261,  339,   54,  260,   54,   54,   54,   54,   54,
       54,   54,   61,  259,   61,  258,   61,   61,   61,   61,

       61,   94,   94,   94,   94,   54,   54,  257,   54,  256,
      255,   54,   61,   61,  254,   61,  253,  252,   61,  148,
      251,  148,  148,  148,  148,  148,  148,  148,  158,  158,
      158,  207,  207,  209,  209,  216,  216,  250,  249,  248,
      247,  246,  245,  244,  243,  242,  241,  240,  239,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  222,  215,  215,   95,  205,   95,
      200,  199,  194,  190,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,
      171,  170,  169,  168,  167,   62,  164,  163,  157,  145,

      132,  131,  128,  123,  122,  119,  108,  107,   97,   91,
       86,   63,   62,   53,  385,    3,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385

    } ;

static yyconst flex_int16_t yy_chk[793] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,    9,    9,   10,
       15,  382,   18,   17,   18,   18,   18,   18,   18,   29,
       24,   19,   29,   15,   17,   17,   19,   10,   26,   26,

       36,   37,   44,   44,   50,   19,   24,   36,   24,   24,
       37,   39,   44,   36,   39,   44,    8,   20,   41,   20,
       20,   20,   20,   20,   38,   41,   38,   54,   61,  381,
       33,   33,   33,   75,   20,   38,   33,   81,   33,   20,
       33,   78,   33,   33,   20,   20,   78,   95,   46,  125,
       33,   46,   79,   50,   81,   20,   55,   55,  380,   55,
       75,   20,   81,   46,   84,   61,  125,   54,  131,   20,
      131,   78,   20,   21,   79,   21,   21,   21,   21,   21,
       56,   56,   56,   62,   62,   62,   84,   95,   83,  130,
       21,   55,   98,   83,  379,   21,   55,  130,  153,   98,

       21,   77,  378,   77,   46,   85,   77,   77,   77,   77,
       77,   21,   70,   70,   70,   70,   70,   21,   83,  121,
      377,   55,   85,  153,  123,   21,  121,   70,   70,  126,
       85,  137,   70,   56,  123,  123,   62,   74,   74,   74,
       74,   74,  135,  135,  126,  135,  137,  159,   70,   70,
      179,  179,   74,   74,   70,  138,  216,   74,   76,  376,
       76,   76,   76,   76,   76,  374,  373,  138,  138,  138,
      217,  139,  159,   74,   74,   76,  220,  135,  142,   74,
      216,  143,  135,  139,  139,  139,  371,  142,  142,  142,
      143,  143,  143,  364,  217,  138,   76,  146,  220,  146,

      363,  362,  146,  146,  146,  146,  146,  135,  361,  356,
      269,  139,  158,  263,  149,  142,  149,  265,  143,  149,
      149,  149,  149,  149,  151,  151,  151,  151,  151,  152,
      152,  152,  152,  152,  158,  269,  158,  208,  206,  158,
      210,  210,  210,  210,  210,  152,  208,  208,  208,  152,
      206,  206,  206,  263,  265,  313,  158,  355,  353,  352,
      158,  350,  349,  348,  158,  347,  152,  218,  313,  346,
      345,  152,  218,  221,  208,  344,  343,  341,  206,  207,
      211,  211,  211,  211,  211,  212,  212,  212,  212,  212,
      221,  207,  207,  207,  207,  207,  211,  218,  221,  340,

      211,  337,  207,  207,  207,  207,  207,  207,  271,  271,
      271,  271,  271,  336,  335,  328,  327,  211,  323,  207,
      322,  321,  211,  207,  207,  207,  207,  207,  207,  209,
      307,  307,  307,  307,  307,  320,  319,  318,  209,  209,
      209,  209,  209,  213,  213,  213,  213,  213,  317,  209,
      209,  209,  209,  209,  209,  316,  315,  314,  305,  213,
      304,  302,  301,  213,  300,  299,  209,  298,  297,  295,
      209,  209,  209,  209,  209,  209,  294,  293,  292,  290,
      213,  219,  289,  219,  288,  213,  219,  219,  219,  219,
      219,  267,  287,  267,  284,  283,  267,  267,  267,  267,

      267,  268,  282,  268,  281,  280,  268,  268,  268,  268,
      268,  272,  272,  272,  272,  272,  279,  308,  308,  308,
      308,  308,  309,  309,  309,  309,  309,  272,  278,  276,
      275,  272,  274,  308,  273,  262,  261,  308,  259,  258,
      310,  310,  310,  310,  310,  257,  256,  255,  272,  254,
      253,  252,  251,  272,  308,  250,  310,  249,  248,  308,
      310,  246,  244,  243,  240,  239,  238,  237,  234,  232,
      231,  230,  229,  228,  227,  226,  225,  310,  224,  223,
      205,  204,  310,  386,  203,  386,  386,  386,  386,  386,
      386,  386,  387,  202,  387,  201,  387,  387,  387,  387,

      387,  388,  388,  388,  388,  389,  389,  200,  389,  199,
      198,  389,  390,  390,  197,  390,  196,  195,  390,  391,
      194,  391,  391,  391,  391,  391,  391,  391,  392,  392,
      392,  393,  393,  394,  394,  395,  395,  193,  192,  191,
      190,  188,  187,  185,  184,  183,  182,  181,  180,  178,
      177,  176,  175,  174,  173,  172,  171,  170,  169,  168,
      167,  166,  165,  162,  161,  156,  155,  136,  132,  129,
      128,  127,  124,  122,  119,  118,  117,  116,  115,  114,
      113,  112,  111,  110,  109,  108,  107,  106,  105,  104,
      103,  102,  101,  100,   99,   96,   93,   89,   80,   69,

       48,   47,   45,   43,   42,   40,   35,   34,   32,   25,
       22,   14,   11,    7,    3,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "C-grammar.l"
#line 25 "C-grammar.l"
#include <stdio.h>
#include "C-grammar.tab.h"

extern void yyerror(const char *);  /* prints grammar violation message */

extern int sym_type(const char *);  /* returns type from symbol table */

#define sym_type(identifier) IDENTIFIER /* with no symbol table, fake it */

static void comment(void);
static int check_type(void);
#line 779 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 38 "C-grammar.l"

#line 995 "lex.yy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 386 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 716 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 39 "C-grammar.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 40 "C-grammar.l"
{ /* consume //-comment */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 42 "C-grammar.l"
{ return(AUTO); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 43 "C-grammar.l"
{ return(BREAK); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 44 "C-grammar.l"
{ return(CASE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 45 "C-grammar.l"
{ return(CHAR); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 46 "C-grammar.l"
{ return(CONST); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 47 "C-grammar.l"
{ return(CONTINUE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 48 "C-grammar.l"
{ return(DEFAULT); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 49 "C-grammar.l"
{ return(DO); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 50 "C-grammar.l"
{ return(DOUBLE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 51 "C-grammar.l"
{ return(ELSE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 52 "C-grammar.l"
{ return(ENUM); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 53 "C-grammar.l"
{ return(EXTERN); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 "C-grammar.l"
{ return(FLOAT); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 55 "C-grammar.l"
{ return(FOR); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 56 "C-grammar.l"
{ return(GOTO); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 57 "C-grammar.l"
{ return(IF); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 58 "C-grammar.l"
{ return(INLINE); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 59 "C-grammar.l"
{ return(INT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 60 "C-grammar.l"
{ return(LONG); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 61 "C-grammar.l"
{ return(REGISTER); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 "C-grammar.l"
{ return(RESTRICT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "C-grammar.l"
{ return(RETURN); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 64 "C-grammar.l"
{ return(SHORT); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 65 "C-grammar.l"
{ return(SIGNED); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 66 "C-grammar.l"
{ return(SIZEOF); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 67 "C-grammar.l"
{ return(STATIC); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 68 "C-grammar.l"
{ return(STRUCT); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 69 "C-grammar.l"
{ return(SWITCH); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 70 "C-grammar.l"
{ return(TYPEDEF); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 71 "C-grammar.l"
{ return(UNION); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 72 "C-grammar.l"
{ return(UNSIGNED); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 73 "C-grammar.l"
{ return(VOID); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 74 "C-grammar.l"
{ return(VOLATILE); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 75 "C-grammar.l"
{ return(WHILE); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 76 "C-grammar.l"
{ return ALIGNAS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 77 "C-grammar.l"
{ return ALIGNOF; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 78 "C-grammar.l"
{ return ATOMIC; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 79 "C-grammar.l"
{ return BOOL; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 80 "C-grammar.l"
{ return COMPLEX; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 81 "C-grammar.l"
{ return GENERIC; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 82 "C-grammar.l"
{ return IMAGINARY; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 83 "C-grammar.l"
{ return NORETURN; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 84 "C-grammar.l"
{ return STATIC_ASSERT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 85 "C-grammar.l"
{ return THREAD_LOCAL; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 86 "C-grammar.l"
{ return FUNC_NAME; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 88 "C-grammar.l"
{ return check_type(); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 90 "C-grammar.l"
{ return I_CONSTANT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 91 "C-grammar.l"
{ return I_CONSTANT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 92 "C-grammar.l"
{ return I_CONSTANT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 93 "C-grammar.l"
{ return I_CONSTANT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 95 "C-grammar.l"
{ return F_CONSTANT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 96 "C-grammar.l"
{ return F_CONSTANT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "C-grammar.l"
{ return F_CONSTANT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "C-grammar.l"
{ return F_CONSTANT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 99 "C-grammar.l"
{ return F_CONSTANT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 100 "C-grammar.l"
{ return F_CONSTANT; }
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 102 "C-grammar.l"
{ return STRING_LITERAL; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 104 "C-grammar.l"
{ return ELLIPSIS; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 105 "C-grammar.l"
{ return RIGHT_ASSIGN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 106 "C-grammar.l"
{ return LEFT_ASSIGN; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 107 "C-grammar.l"
{ return ADD_ASSIGN; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 108 "C-grammar.l"
{ return SUB_ASSIGN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 109 "C-grammar.l"
{ return MUL_ASSIGN; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 110 "C-grammar.l"
{ return DIV_ASSIGN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 111 "C-grammar.l"
{ return MOD_ASSIGN; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 112 "C-grammar.l"
{ return AND_ASSIGN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 113 "C-grammar.l"
{ return XOR_ASSIGN; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 114 "C-grammar.l"
{ return OR_ASSIGN; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 115 "C-grammar.l"
{ return RIGHT_OP; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 116 "C-grammar.l"
{ return LEFT_OP; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 117 "C-grammar.l"
{ return INC_OP; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 118 "C-grammar.l"
{ return DEC_OP; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 119 "C-grammar.l"
{ return PTR_OP; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 120 "C-grammar.l"
{ return AND_OP; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 121 "C-grammar.l"
{ return OR_OP; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 122 "C-grammar.l"
{ return LE_OP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 123 "C-grammar.l"
{ return GE_OP; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 124 "C-grammar.l"
{ return EQ_OP; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 125 "C-grammar.l"
{ return NE_OP; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 126 "C-grammar.l"
{ return ';'; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 127 "C-grammar.l"
{ return '{'; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 128 "C-grammar.l"
{ return '}'; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 129 "C-grammar.l"
{ return ','; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 130 "C-grammar.l"
{ return ':'; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 131 "C-grammar.l"
{ return '='; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 132 "C-grammar.l"
{ return '('; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 133 "C-grammar.l"
{ return ')'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 134 "C-grammar.l"
{ return '['; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 135 "C-grammar.l"
{ return ']'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 136 "C-grammar.l"
{ return '.'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 137 "C-grammar.l"
{ return '&'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 138 "C-grammar.l"
{ return '!'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 139 "C-grammar.l"
{ return '~'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 140 "C-grammar.l"
{ return '-'; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 141 "C-grammar.l"
{ return '+'; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 142 "C-grammar.l"
{ return '*'; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 143 "C-grammar.l"
{ return '/'; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 144 "C-grammar.l"
{ return '%'; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 145 "C-grammar.l"
{ return '<'; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 146 "C-grammar.l"
{ return '>'; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 147 "C-grammar.l"
{ return '^'; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 148 "C-grammar.l"
{ return '|'; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 149 "C-grammar.l"
{ return '?'; }
	YY_BREAK
case 106:
/* rule 106 can match eol */
YY_RULE_SETUP
#line 151 "C-grammar.l"
{ /* whitespace separates tokens */ }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 152 "C-grammar.l"
{ /* discard bad characters */ }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 154 "C-grammar.l"
ECHO;
	YY_BREAK
#line 1594 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 386 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 386 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 385);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 153 "C-grammar.l"



int yywrap(void)        /* called at end of input */
{
    return 1;           /* terminate now */
}

static void comment(void)
{
    int c;

    while ((c = input()) != 0)
        if (c == '*')
        {
            while ((c = input()) == '*')
                ;

            if (c == '/')
                return;

            if (c == 0)
                break;
        }
    yyerror("unterminated comment");
}

static int check_type(void)
{
    switch (sym_type(yytext))
    {
    case TYPEDEF_NAME:                /* previously defined */
        return TYPEDEF_NAME;
    case ENUMERATION_CONSTANT:        /* previously defined */
        return ENUMERATION_CONSTANT;
    default:                          /* includes undefined */
        return IDENTIFIER;
    }
}

